import java.io.IOException;
import java.sql.* ;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.servlet.Servlet;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.sql.DataSource;

import org.commonmark.node.*;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;
import com.mysql.jdbc.Driver;

/**
 * Servlet implementation class for Servlet: ConfigurationTest
 *
 */
public class Editor extends HttpServlet {
    /**
     * The Servlet constructor
     * 
     * @see javax.servlet.http.HttpServlet#HttpServlet()
     */
    public Editor() {}

    public void init() throws ServletException
    {
        /*  write any servlet initialization code here or remove this function */
        controller = new MDController();
    }
    
    public void destroy()
    {
        /*  write any servlet cleanup code here or remove this function */
    }

    /**
     * Handles HTTP GET requests
     * 
     * @see javax.servlet.http.HttpServlet#doGet(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
        String op = String.valueOf(request.getAttribute("action"));
	// implement your GET method handling code here
	// currently we simply show the page generated by "edit.jsp"
        request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }
    
    /**
     * Handles HTTP POST requests
     * 
     * @see javax.servlet.http.HttpServlet#doPost(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
        String action = String.valueOf(request.getAttribute("action"));
        if(action.equals("open")){

        }
	// implement your POST method handling code here
	// currently we simply show the page generated by "edit.jsp"
        request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }

    // Invalid condition: 1 stands for username missing, 2 stands for postid missing
    public int handleOpen(HttpServletRequest request, HttpServletResponse response){
        Object username = request.getAttribute("username");
        Object postid = request.getAttribute("postid");
        if(username == null){return 1;}
        if(postid == null){return 2;}
        String usr = String.valueOf(username);
        String id = String.valueOf(postid);

    }


}

// controller class
class Controller {
    public Controller() {}

    public void open(HttpServletRequest request, HttpServletResponse response) {

    }

    public void save(HttpServletRequest request, HttpServletResponse response) {

    }

    public void delete(HttpServletRequest request, HttpServletResponse response) {

    }

    public void preview(HttpServletRequest request, HttpServletResponse response) {

    }

    public void list(HttpServletRequest request, HttpServletResponse response) {

    }
}


class Database {
    public Database() {}
}
